### ISSUE TITLE
Trailer link is not working.

### ISSUE THREAD

**Issue by gsbenevides2** [AmandaAmorim/projeto-mario#1]
The link to embed video of youtube is not valid and show this message in my screen:
![image](https://user-images.githubusercontent.com/45762112/219955559-dbce83b6-5982-4963-a380-d99f3c7a82be.png)

I sugest to change this:
https://youtube.com/embed/Cb4WV4aXBpks
to this:
https://youtube.com/embed/cDNkh5WybZo

This is link to trailler in portuguese of ingresso.com youtube channel.

**Comment by AmandaAmorim** [comment]
I changed the links, try access again. Thanks for the feedback!
